name: On Push Handling - 2

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  issues: write

jobs:
  call-shared-workflow:
    uses: pft-TommyChang/Sirius-Release/issue_commit_reuseable.yml@main
    secrets: inherit
